# By default, SwiftLint uses a set of sensible default rules you can adjust:
disabled_rules: # rule identifiers turned on by default to exclude from running
  - file_length
  - type_body_length
  - cyclomatic_complexity
  - function_body_length
  - switch_case_alignment
  - identifier_name  # Disable strict identifier naming rules
  - force_try  # Allow force try statements
  - type_name  # Allow flexible type naming conventions
  - force_cast  # Allow force casts

line_length:
  warning: 180
  ignores_comments: true

type_name:
  allowed_symbols: "_"

excluded: 
  - Package.swift
  - .build
  - .swiftpm
  - DerivedData
  - Carthage
  - Pods
  - .build/**
  - "**/Package.swift"
  - "**/.build/**"
  - "**/checkouts/**"
  - "**/SourcePackages/**"
  - "**/DerivedData/**"
